// components/header-home.vue
<template>
    <header class="w-screen flex flex-row items-center h-[6vh] bg-primary">
        <div class="flex-grow-0 h-full flex items-center">
            <img src="/assets/svg/cardapiogo.svg" alt="Logotipo Cardápiogo" class="h-full md:h-full">
        </div>
        <nav class="flex flex-row justify-end items-center flex-grow w-full h-full px-[6vw] space-x-[4vw]">
            <ButtonsLink to="/" variant="default">Criar Conta</ButtonsLink>
            <ButtonsLink to="/" variant="secondary">Entrar</ButtonsLink>
        </nav>
    </header>
</template>

// src/app/components/header/headerHome.tsx
'use client'
import { Bars3Icon } from "@heroicons/react/24/solid";
import { useState } from "react";
import { DialogMenu, type DialogMenuItem } from "../menu/dialogMenu";

export function HeaderHome() {
  const [mobileMenu, setMobileMenu] = useState(false);

  const items: DialogMenuItem[] = [
    { href: "/sign-in", text: "Entrar" },
    { href: "/sign-up", text: "Criar Conta" },
    { href: "/search", text: "Buscar lojas e restaurantes" },
    { href: "/sign-up-store", text: "Anuncie sua loja e restaurante" }
  ]

  return (
    <header className="bg-red-600 h-12 w-full fixed flex flex-row items-center justify-between text-white">
      <nav className="flex flex-row items-center justify-end p-4">
        <a href="/">
        <img src="./cardapiogo/cardapiogo-white.svg" alt="Logo Cardapiogo" className="h-8 w-8" />
        </a>
      </nav>
      <nav className="flex flex-row items-center justify-end p-4">
        <button type="button" onClick={() => setMobileMenu(!mobileMenu)}>
          <Bars3Icon className="h-8 w-8 transform transition-transform hover:scale-110" />
        </button>
      </nav>
      <DialogMenu isOpen={mobileMenu} items={items}/>
    </header>
  );
}
